const http=require('http');const jwt=require('jsonwebtoken');const Database=require('better-sqlite3');const path=require('path');
const PORT=process.env.SECURITY_PORT||3002;const JWT_SECRET=process.env.JWT_SECRET||'locly-dev-secret-change-me';const db=new Database(path.join(__dirname,'data','locly.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS security_events(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,severity TEXT NOT NULL DEFAULT 'info',ip TEXT,user_id INTEGER,details TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_security_events_created ON security_events(created_at);CREATE INDEX IF NOT EXISTS idx_security_events_ip ON security_events(ip);`);
const json=(res,status,b)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Allow-Methods':'GET,OPTIONS'});res.end(JSON.stringify(b))};
const clientIp=req=>(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim().replace(/^::ffff:/,'');
function admin(req,res){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;try{const t=jwt.verify(h.slice(7),JWT_SECRET);const u=db.prepare('SELECT * FROM users WHERE id=?').get(t.id);if(!u||u.status!=='active'||!['admin','superadmin','moderator','finance'].includes(u.role))return null;req.dbUser=u;return u}catch{return null}}
function cleanup(){db.prepare("DELETE FROM security_events WHERE created_at < datetime('now','-30 days')").run()}
function overview(){cleanup();const online=db.prepare("SELECT COUNT(*) n FROM presence_sessions WHERE last_seen>=datetime('now','-90 seconds')").get().n;const accounts=db.prepare("SELECT COUNT(DISTINCT user_id) n FROM presence_sessions WHERE user_id IS NOT NULL AND last_seen>=datetime('now','-90 seconds')").get().n;const shared=db.prepare("SELECT ip,COUNT(DISTINCT user_id) accounts,COUNT(*) sessions FROM presence_sessions WHERE last_seen>=datetime('now','-90 seconds') GROUP BY ip HAVING COUNT(DISTINCT user_id)>1 ORDER BY accounts DESC LIMIT 50").all();const userIps=db.prepare("SELECT user_id,COUNT(DISTINCT ip) ips,GROUP_CONCAT(DISTINCT ip) addresses FROM presence_sessions WHERE last_seen>=datetime('now','-24 hours') AND user_id IS NOT NULL GROUP BY user_id HAVING COUNT(DISTINCT ip)>1 ORDER BY ips DESC LIMIT 50").all();const blocked=db.prepare("SELECT COUNT(*) n FROM ip_controls WHERE action='blocked' AND (expires_at IS NULL OR expires_at>datetime('now'))").get().n;const recent=db.prepare("SELECT e.*,u.name user_name,u.email FROM security_events e LEFT JOIN users u ON u.id=e.user_id ORDER BY e.created_at DESC LIMIT 100").all();return{online,accounts,sharedIpAlerts:shared,userIpChanges:userIps,blockedIps:blocked,recentEvents:recent}}
const server=http.createServer((req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});if(req.url==='/api/security/overview'&&req.method==='GET'){const u=admin(req,res);if(!u)return json(res,403,{error:'Accès sécurité refusé'});if(!['admin','superadmin'].includes(u.role))return json(res,403,{error:'Centre sécurité réservé aux administrateurs'});return json(res,200,overview())}if(req.url==='/api/security/events'&&req.method==='GET'){const u=admin(req,res);if(!u||!['admin','superadmin'].includes(u.role))return json(res,403,{error:'Accès refusé'});const rows=db.prepare("SELECT e.*,u.name user_name,u.email FROM security_events e LEFT JOIN users u ON u.id=e.user_id ORDER BY e.created_at DESC LIMIT 300").all();return json(res,200,{events:rows})}return json(res,404,{error:'Not found'})});
server.listen(PORT,()=>console.log(`Locly Security Center listening on :${PORT}`));